services:
  - type: web
    name: vampire-md
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: AUTO_LOGIN
        value: "true"
      - key: BOT_NAME
        value: Vampire MD
      - key: PREFIX
        value: "."
      - key: SESSION_ID
        value: "your-session-id-here"
